"""Phoenix MMI read-only firmware research SDK."""

from .analysis import AnalysisConfig, analyze_file, compare_reports
from .accessor_dispatch import (
    analyze_accessor_dispatch,
    build_public_accessor_dispatch_report,
    correlate_accessor_dispatch,
    update_operational_graph_v11,
)
from .binary import BinaryReader
from .checksum import ChecksumExpectation, ChecksumMatch, crc32_bytes
from .cross_payload_homolog import (
    PayloadInput,
    analyze_cross_payload_homologs,
    build_public_cross_payload_homolog_report,
    correlate_cross_payload_homologs,
    derive_cross_payload_signature,
    payload_member_eligible,
    update_operational_graph_v33,
)
from .record_normalization import (
    DecodedRegion,
    NormalizationResult,
    RecordPayloadInput,
    analyze_record_normalized_homologs,
    build_public_record_normalized_homolog_report,
    correlate_record_normalized_homologs,
    decode_intel_hex,
    decode_srecord_envelope,
    normalize_record_payload,
    record_member_eligible,
    update_operational_graph_v34,
)
from .call_return_producer import (
    analyze_call_return_producer,
    build_public_call_return_producer_report,
    correlate_call_return_producer,
    update_operational_graph_v19,
)
from .continuation_contract import (
    analyze_internal_continuation_contract,
    build_public_internal_continuation_report,
    correlate_internal_continuation_contract,
    update_operational_graph_v16,
)
from .descriptor_lineage import (
    analyze_descriptor_lineage,
    build_public_descriptor_lineage_report,
    correlate_descriptor_lineage,
    trace_dispatch_producer,
    update_operational_graph_v10,
)
from .entropy import EntropyWindow, entropy_profile, shannon_entropy
from .exact_block_map import (
    analyze_exact_block_map,
    build_public_exact_block_map_report,
    compare_exact_block_seed_control,
    correlate_exact_block_map,
    update_operational_graph_v27,
)
from .dual_delta_similarity import (
    analyze_dual_delta_similarity,
    build_public_dual_delta_similarity_report,
    compare_similarity_grid_control,
    correlate_dual_delta_similarity,
    finalize_dual_delta_similarity,
    update_operational_graph_v28,
)
from .fingerprint import FingerprintHit, scan_fingerprints
from .handoff_field60 import (
    analyze_handoff_field60,
    build_public_handoff_field60_report,
    correlate_handoff_field60,
    update_operational_graph_v21,
)
from .handoff_mapping import (
    analyze_handoff_mapping,
    build_public_handoff_mapping_report,
    correlate_handoff_mapping,
    update_operational_graph_v22,
)
from .island_atlas import (
    analyze_content_island_atlas,
    build_public_content_island_atlas_report,
    compare_island_atlas_grid_control,
    correlate_content_island_atlas,
    finalize_content_island_atlas,
    update_operational_graph_v29,
)
from .layout import analyze_executable_layout
from .literal_pool_boundary import (
    analyze_literal_pool_boundaries,
    build_public_literal_pool_boundary_report,
    correlate_literal_pool_boundaries,
    update_operational_graph_v23,
)
from .piecewise_link_map import (
    analyze_piecewise_link_map,
    build_public_piecewise_link_map_report,
    correlate_piecewise_link_map,
    update_operational_graph_v24,
)
from .relocation_breakpoints import (
    analyze_relocation_breakpoints,
    build_public_relocation_breakpoint_report,
    correlate_relocation_breakpoints,
    update_operational_graph_v25,
)
from .relocation_descriptors import (
    analyze_relocation_descriptors,
    build_public_relocation_descriptor_report,
    correlate_relocation_descriptors,
    update_operational_graph_v26,
)
from .map_media import (
    analyze_navigation_media,
    build_public_navigation_media_report,
    correlate_firmware_and_media,
    parse_fldb_container,
    probe_firmware_media_markers,
    update_operational_graph_v4,
)
from .map_payload import (
    analyze_navigation_payloads,
    build_public_navigation_payload_report,
    classify_payload_header,
)
from .micro_island import (
    analyze_micro_island,
    build_public_micro_island_report,
    correlate_micro_island,
    update_operational_graph_v30,
)
from .navigation_dataflow import (
    analyze_navigation_dataflow,
    build_public_navigation_dataflow_report,
    compare_navigation_dataflow,
    discover_contract_anchors,
    summarize_code_window,
    summarize_runtime_neighborhood,
    update_operational_graph_v3,
)
from .navigation_storage import (
    analyze_navigation_storage_boundary,
    build_public_navigation_storage_report,
    compare_navigation_storage_boundaries,
    scan_storage_signatures,
    update_operational_graph,
)
from .operational_model import (
    analyze_relocated_bitmap_atlas,
    build_operational_graph,
    build_public_operational_report,
)
from .object_dispatch import (
    analyze_object_dispatch_context,
    build_public_object_dispatch_report,
    correlate_dispatch_context,
    summarize_contextual_dispatch_calls,
    update_operational_graph_v9,
)
from .optical_callgraph import (
    build_bounded_interprocedural_graph,
    build_public_optical_callgraph_report,
    collect_seed_pairs,
    compare_optical_navigation_callgraph,
    correlate_optical_sector_model,
    summarize_bounded_entry,
    update_operational_graph_v8,
)
from .parser_contract import (
    compare_parser_constants,
    correlate_payload_parser_contract,
    scan_parser_constants,
    update_operational_graph_v5,
)
from .parser_dataflow import (
    analyze_fldb_candidate_dataflow,
    build_public_fldb_candidate_report,
    compare_fldb_candidate_dataflow,
    correlate_corrected_parser_model,
    update_operational_graph_v6,
)
from .parser_search import (
    build_public_global_parser_report,
    compare_global_fldb_parser_search,
    correlate_global_fldb_parser_search,
    scan_global_fldb_parser_candidates,
    update_operational_graph_v7,
)
from .producer_return_family import (
    analyze_producer_return_family,
    build_public_producer_return_report,
    correlate_producer_return_family,
    update_operational_graph_v20,
)
from .reference_graph import (
    analyze_reference_graph,
    build_public_reference_graph,
    compare_reference_graphs,
)
from .resource_bundle import analyze_resource_bundle, build_public_resource_bundle
from .runtime_map import analyze_runtime_map, build_public_runtime_map
from .runtime_slot import (
    analyze_runtime_slot_lineage,
    build_public_runtime_slot_report,
    correlate_runtime_slot_lineage,
    update_operational_graph_v12,
)
from .run_gap_topology import (
    analyze_run_gap_topology,
    build_public_run_gap_report,
    correlate_run_gap_topology,
    update_operational_graph_v31,
)
from .registered_provenance import (
    analyze_registered_provenance,
    build_public_registered_provenance_report,
    build_registered_evidence,
    correlate_registered_provenance,
    evaluate_registered_pairs,
    update_operational_graph_v32,
)
from .runtime_linkage import (
    analyze_runtime_linkage_family,
    build_public_runtime_linkage_report,
    correlate_runtime_linkage_family,
    update_operational_graph_v13,
)
from .linkage_owner import (
    analyze_linkage_owner_lineage,
    build_public_linkage_owner_report,
    correlate_linkage_owner_lineage,
    update_operational_graph_v14,
)
from .owner_provenance import (
    analyze_owner_ingress_state,
    build_public_owner_ingress_report,
    correlate_owner_ingress_state,
    update_operational_graph_v15,
)
from .owner_caller import (
    analyze_owner_caller_compatibility,
    build_public_owner_caller_report,
    correlate_owner_caller_compatibility,
    update_operational_graph_v17,
)
from .owner_producer import (
    analyze_owner_producer_candidates,
    build_public_owner_producer_report,
    correlate_owner_producer_candidates,
    update_operational_graph_v18,
)
from .segments import CandidateSegment, build_candidate_segments
from .superh import (
    SHInstruction,
    decode_instruction,
    decode_instruction_extended,
    trace_control_flow,
)

__all__ = [
    "AnalysisConfig",
    "BinaryReader",
    "CandidateSegment",
    "ChecksumExpectation",
    "ChecksumMatch",
    "DecodedRegion",
    "NormalizationResult",
    "PayloadInput",
    "RecordPayloadInput",
    "EntropyWindow",
    "FingerprintHit",
    "SHInstruction",
    "analyze_file",
    "analyze_internal_continuation_contract",
    "analyze_call_return_producer",
    "analyze_accessor_dispatch",
    "analyze_descriptor_lineage",
    "analyze_executable_layout",
    "analyze_exact_block_map",
    "analyze_dual_delta_similarity",
    "analyze_fldb_candidate_dataflow",
    "analyze_handoff_field60",
    "analyze_handoff_mapping",
    "analyze_content_island_atlas",
    "analyze_cross_payload_homologs",
    "analyze_record_normalized_homologs",
    "analyze_navigation_storage_boundary",
    "analyze_navigation_dataflow",
    "analyze_navigation_media",
    "analyze_navigation_payloads",
    "analyze_micro_island",
    "analyze_object_dispatch_context",
    "analyze_reference_graph",
    "analyze_relocated_bitmap_atlas",
    "analyze_resource_bundle",
    "analyze_runtime_map",
    "analyze_runtime_slot_lineage",
    "analyze_run_gap_topology",
    "analyze_registered_provenance",
    "analyze_runtime_linkage_family",
    "analyze_linkage_owner_lineage",
    "analyze_literal_pool_boundaries",
    "analyze_piecewise_link_map",
    "analyze_relocation_breakpoints",
    "analyze_relocation_descriptors",
    "analyze_owner_ingress_state",
    "analyze_owner_caller_compatibility",
    "analyze_owner_producer_candidates",
    "analyze_producer_return_family",
    "build_candidate_segments",
    "build_public_accessor_dispatch_report",
    "build_operational_graph",
    "build_bounded_interprocedural_graph",
    "build_public_optical_callgraph_report",
    "build_public_navigation_storage_report",
    "build_public_fldb_candidate_report",
    "build_public_descriptor_lineage_report",
    "build_public_exact_block_map_report",
    "build_public_dual_delta_similarity_report",
    "build_public_global_parser_report",
    "build_public_handoff_field60_report",
    "build_public_handoff_mapping_report",
    "build_public_content_island_atlas_report",
    "build_public_cross_payload_homolog_report",
    "build_public_record_normalized_homolog_report",
    "build_public_navigation_dataflow_report",
    "build_public_navigation_media_report",
    "build_public_navigation_payload_report",
    "build_public_micro_island_report",
    "build_public_operational_report",
    "build_public_object_dispatch_report",
    "build_public_reference_graph",
    "build_public_resource_bundle",
    "build_public_runtime_map",
    "build_public_runtime_slot_report",
    "build_public_run_gap_report",
    "build_public_registered_provenance_report",
    "build_registered_evidence",
    "build_public_runtime_linkage_report",
    "build_public_linkage_owner_report",
    "build_public_literal_pool_boundary_report",
    "build_public_piecewise_link_map_report",
    "build_public_relocation_breakpoint_report",
    "build_public_relocation_descriptor_report",
    "build_public_owner_ingress_report",
    "build_public_owner_caller_report",
    "build_public_owner_producer_report",
    "build_public_internal_continuation_report",
    "build_public_call_return_producer_report",
    "build_public_producer_return_report",
    "compare_reports",
    "compare_exact_block_seed_control",
    "compare_similarity_grid_control",
    "compare_navigation_storage_boundaries",
    "compare_island_atlas_grid_control",
    "compare_navigation_dataflow",
    "compare_optical_navigation_callgraph",
    "compare_parser_constants",
    "compare_fldb_candidate_dataflow",
    "compare_global_fldb_parser_search",
    "classify_payload_header",
    "correlate_payload_parser_contract",
    "correlate_accessor_dispatch",
    "correlate_corrected_parser_model",
    "correlate_descriptor_lineage",
    "correlate_exact_block_map",
    "correlate_dual_delta_similarity",
    "finalize_dual_delta_similarity",
    "correlate_global_fldb_parser_search",
    "correlate_handoff_field60",
    "correlate_handoff_mapping",
    "correlate_content_island_atlas",
    "correlate_cross_payload_homologs",
    "correlate_record_normalized_homologs",
    "correlate_firmware_and_media",
    "correlate_micro_island",
    "correlate_runtime_slot_lineage",
    "correlate_run_gap_topology",
    "correlate_registered_provenance",
    "correlate_runtime_linkage_family",
    "correlate_linkage_owner_lineage",
    "correlate_literal_pool_boundaries",
    "correlate_piecewise_link_map",
    "correlate_relocation_breakpoints",
    "correlate_relocation_descriptors",
    "correlate_owner_ingress_state",
    "correlate_owner_caller_compatibility",
    "correlate_owner_producer_candidates",
    "correlate_internal_continuation_contract",
    "correlate_call_return_producer",
    "correlate_producer_return_family",
    "correlate_optical_sector_model",
    "correlate_dispatch_context",
    "compare_reference_graphs",
    "crc32_bytes",
    "collect_seed_pairs",
    "decode_instruction",
    "decode_instruction_extended",
    "decode_intel_hex",
    "decode_srecord_envelope",
    "derive_cross_payload_signature",
    "discover_contract_anchors",
    "entropy_profile",
    "parse_fldb_container",
    "payload_member_eligible",
    "normalize_record_payload",
    "probe_firmware_media_markers",
    "record_member_eligible",
    "scan_fingerprints",
    "scan_parser_constants",
    "scan_global_fldb_parser_candidates",
    "scan_storage_signatures",
    "shannon_entropy",
    "summarize_code_window",
    "summarize_bounded_entry",
    "summarize_contextual_dispatch_calls",
    "summarize_runtime_neighborhood",
    "trace_control_flow",
    "trace_dispatch_producer",
    "finalize_content_island_atlas",
    "evaluate_registered_pairs",
    "update_operational_graph",
    "update_operational_graph_v3",
    "update_operational_graph_v4",
    "update_operational_graph_v5",
    "update_operational_graph_v6",
    "update_operational_graph_v7",
    "update_operational_graph_v8",
    "update_operational_graph_v9",
    "update_operational_graph_v10",
    "update_operational_graph_v11",
    "update_operational_graph_v12",
    "update_operational_graph_v13",
    "update_operational_graph_v14",
    "update_operational_graph_v15",
    "update_operational_graph_v16",
    "update_operational_graph_v17",
    "update_operational_graph_v18",
    "update_operational_graph_v19",
    "update_operational_graph_v20",
    "update_operational_graph_v21",
    "update_operational_graph_v22",
    "update_operational_graph_v23",
    "update_operational_graph_v24",
    "update_operational_graph_v25",
    "update_operational_graph_v26",
    "update_operational_graph_v27",
    "update_operational_graph_v28",
    "update_operational_graph_v29",
    "update_operational_graph_v30",
    "update_operational_graph_v31",
    "update_operational_graph_v32",
    "update_operational_graph_v33",
    "update_operational_graph_v34",
]

__version__ = "0.39.0"
